Repository marceljungle/eHealthSupermarket, pull requests merged in 2021-03, with the labels that each got.

#10 implemented login register funcionality. Read more...
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/LoginActivity.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/MainActivity.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ResetPasswordActivity.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/SignupActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/mipmap-hdpi/logo.png
  app/src/main/res/mipmap-mdpi/logo.png
  app/src/main/res/mipmap-xhdpi/logo.png
  app/src/main/res/mipmap-xxhdpi/logo.png
  app/src/main/res/mipmap-xxxhdpi/logo.png
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement

#13 Added some examples for testing Firebase database.
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/LoginActivity.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/SignupActivity.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/home/homeFragment.java
Labels: bug, enhancement

#15 implmented reset_password, added log_out button in account_fragment. Read more...
  app/build.gradle
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/LoginActivity.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ResetPasswordActivity.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/SignupActivity.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/accountSetting.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/activity_productview.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/account/accountFragment.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/home/homeFragment.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/list/CustomAdapter.java
  app/src/main/res/drawable/ic_baseline_exit_to_app_24.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_productview.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/layout/activity_signup.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mylist_row.xml
Labels: bug, enhancement

#17 Develop sergypl
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/Product_Adapter.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/activity_products_listview.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/activity_productview.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/dbCollections/Product.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/home/homeFragment.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/list/mylistFragment.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/list/mylistProducts.java
  app/src/main/res/drawable/ic_dislike_selected.xml
  app/src/main/res/drawable/ic_dislike_unselected.xml
  app/src/main/res/drawable/ic_like_selected.xml
  app/src/main/res/drawable/ic_like_unselect.xml
  app/src/main/res/layout/activity_mylist_products.xml
  app/src/main/res/layout/activity_products_listview.xml
  app/src/main/res/layout/activity_productview.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/grid_item_product.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#26 Improved the grid view and implemented the individual product view
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ActivityProductView.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ActivityProductsListView.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/LoginActivity.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ProductAdapter.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/collections/Additive.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/collections/Intolerance.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/collections/Product.java
  app/src/main/res/layout/activity_productview.xml
  app/src/main/res/layout/grid_item_product.xml
Labels: bug, enhancement

#28 Implementation of QR Code Scan funcionality
  app/build.gradle
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ActivityProductView.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/scan/ScanFragment.java
Labels: enhancement

#29 Added Intolerances handler including logic and Views
  .idea/.gitignore
  .idea/checkstyle-idea.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/AddIntolerancesOrAdditives.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/AddIntolerancesOrAdditivesAdapter.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/account/AccountFragment.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/intolerances/IntoleranceFragment.java
  app/src/main/res/drawable/baseline_search_black_24dp.xml
  app/src/main/res/layout/activity_add_intolerances_or_additives.xml
  app/src/main/res/layout/custom_intolerance_item.xml
  app/src/main/res/layout/fragment_account.xml
  app/src/main/res/layout/fragment_intolerances.xml
  app/src/main/res/layout/fragment_mylist.xml
  app/src/main/res/menu/searchfile.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#31 Modified the product view.
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ActivityProductView.java
  app/src/main/res/drawable/border_button_pressed.xml
  app/src/main/res/drawable/border_button_unpressed.xml
  app/src/main/res/layout/activity_productview.xml
Labels: bug

#37 Changes in appearance of home fragment. Read more...
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ActivityProductView.java
  app/src/main/java/com/gmail/gigi/dan2011/ehealthsupermarket/ui/home/HomeFragment.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_scan.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement
